app:
  log_level: "debug"
  server_port: 8081
  enable_ui: true
  rod_browser_bin: "/opt/homebrew/bin/chromium"

template_storage:
  storage_type: "mysql"

file_storage:
  storage_type: "disk"

browser:
  tab_pool: 50

workerpool:
  worker_count: 6
  worker_timeout_ms: 310 # milliseconds

s3:
  endpoint: "http://localstack:4566"
  debug: false
  region: "us-west-2"
  force_path_style: true
  uploader_concurrency: 5
  # 5MB chunks
  uploader_part_size_mb: 5
  downloader_concurrency: 5
  # 5MB chunks
  downloader_part_size_mb: 5242880
  retry_max_attempts: 3
  bucket: "local-bucket"
  use_custom_transport: false

aws:
  access_key_id: "xxxxx-xxxxx-xxxxx-xxxxx-xxxxx"
  secret_access_key: "xxxxx-xxxxx-xxxxx-xxxxx-xxxxx"
  session_token: ""

certificates:
  cert1:
    cert_path: "./inputfiles/certificates/cert.pem"
    key_path: "./inputfiles/certificates/key_pkcs8_encrypted.pem"
    key_password: "test"
  cert2:
    cert_path: "./certificates/certificate2.pem"
    key_path: "./certificates/pirvatekey2.key"
    key_password: "password2"

db:
  host: "mysql"
  port: 3306
  username: "pdf_user"
  password: "pdf_password"
  database: "pdf_templates"