package config

const (
	CONFIG_FILE_NAME = "CONFIG_FILE_NAME"
	CONFIG_FILE_TYPE = "CONFIG_FILE_TYPE"
	CONFIG_FILE_PATH = "CONFIG_FILE_PATH"

	ENABLE_UI       = "ENABLE_UI"
	ROD_BROWSER_BIN = "ROD_BROWSER_BIN"
)
